// header-mode-hmac.test.js — behavioral coverage for the HMAC
// proof-of-gateway verification shipped in dde6095 + 71c2506
// (companion to operatum-ui#576, the gateway-side signer).
//
// Three layers:
//   1. GATEWAY-FIXTURE drift pin — a header set + canonical string +
//      signature generated by RUNNING THE GATEWAY'S SIGNER
//      (gateway/src/lib/operatum-headers.js, buildOperatumHeaders with a
//      known secret + fixed timestamp), hardcoded here. If either side's
//      canonicalization drifts, this fixture stops verifying and the test
//      fails BEFORE production does.
//   2. readOperatumHeaders({secret}) pure-function tests — signed-valid
//      passes; unsigned/forged/wrong-secret/stale/empty fail closed.
//   3. Factory behaviour — OPERATUM_GATEWAY_SIGNING_SECRET (or
//      opts.secret) present at construction ⇒ middleware 401s unsigned
//      headers and passes signed ones; unset (or '') ⇒ legacy
//      presence-only behaviour, so rollout stays per-app opt-in via the
//      platform-injected env var.
//
// The verification internals (canonicalStringForSigning,
// verifyOperatumSignature) are deliberately module-private in
// src/header-mode.js, so everything here goes through the public surface:
// readOperatumHeaders + createOperatumAuthFromHeaders. The canonical
// string is still pinned byte-for-byte below via the fixture: the test
// recomputes HMAC(secret, PINNED_CANONICAL) and requires it to equal the
// gateway-produced signature AND requires main's verifier to accept it —
// which together prove the private canonicalization matches the gateway's.

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import {
  createOperatumAuthFromHeaders,
  readOperatumHeaders,
} from '../src/header-mode.js';

const UUID_USER  = '00000000-0000-0000-0000-000000000001';
const UUID_TEN   = '00000000-0000-0000-0000-000000000002';
const UUID_BUILD = '00000000-0000-0000-0000-000000000003';
const SECRET = 'per-deploy-gateway-app-shared-secret';

// Wire constants of the signed protocol. These mirror the (private)
// values in src/header-mode.js and the gateway's operatum-headers.js;
// the fixture tests below are what keep all three in lockstep.
const TS_HEADER  = 'x-operatum-timestamp';
const SIG_HEADER = 'x-operatum-signature';
const MAX_AGE_MS = 5 * 60 * 1000; // ±5 min replay window
const HEADER_ORDER = [
  'x-operatum-user-id',
  'x-operatum-tenant-id',
  'x-operatum-email',
  'x-operatum-display-name',
  'x-operatum-role',
  'x-operatum-build-id',
  'x-operatum-perms',
  'x-operatum-auth-mode',
];

const baseHeaders = (overrides = {}) => ({
  'x-operatum-user-id':     UUID_USER,
  'x-operatum-tenant-id':   UUID_TEN,
  'x-operatum-email':       'alice%40example.com',
  'x-operatum-role':        'builder',
  'x-operatum-build-id':    UUID_BUILD,
  'x-operatum-perms':       '["use"]',
  'x-operatum-auth-mode':   'reverse-proxy',
  ...overrides,
});

// Test-local copy of the gateway's signer (canonicalization + HMAC).
// Used to mint fresh signed sets for the behavioral cases; the
// cross-repo fixture below is the drift guard proving this copy (and
// the module's private verifier) match the real gateway signer.
function sign(headers, secret, timestamp) {
  const ts = String(timestamp);
  const parts = [];
  for (const name of HEADER_ORDER) {
    const v = headers[name];
    if (v != null) parts.push(`${name}=${v}`);
  }
  parts.push(`${TS_HEADER}=${ts}`);
  const signature = createHmac('sha256', secret).update(parts.join('\n')).digest('hex');
  return { ...headers, [TS_HEADER]: ts, [SIG_HEADER]: signature };
}

const FIXED_TS = 1_700_000_000_000;

function makeRes() {
  const captured = { status: null, body: null };
  return {
    captured,
    status(code) { captured.status = code; return this; },
    json(body)   { captured.body = body; return this; },
  };
}

// ── 1. gateway-generated fixture (drift pin) ───────────────────────────
//
// Generated 2026-07-01 by running the GATEWAY's signer:
//
//   import { buildOperatumHeaders } from 'gateway/src/lib/operatum-headers.js'
//   buildOperatumHeaders({
//     user: { id: …0001, tenant_id: …0002, email: 'alice@example.com',
//             displayName: 'Alice Wonder', role: 'builder' },
//     buildId: …0003, perms: ['use'],
//     secret: 'fixture-shared-secret-do-not-change',
//     timestamp: 1700000000000,
//   })
//
// DO NOT regenerate to make a failing test pass — a mismatch means this
// package's verifier has drifted from the gateway's signer (or vice
// versa), which breaks authentication for every signed app in production.
const GW_FIXTURE_SECRET = 'fixture-shared-secret-do-not-change';
const GW_FIXTURE_TS = 1_700_000_000_000;
const GW_FIXTURE_HEADERS = Object.freeze({
  'x-operatum-user-id': '00000000-0000-0000-0000-000000000001',
  'x-operatum-tenant-id': '00000000-0000-0000-0000-000000000002',
  'x-operatum-email': 'alice%40example.com',
  'x-operatum-role': 'builder',
  'x-operatum-build-id': '00000000-0000-0000-0000-000000000003',
  'x-operatum-perms': '["use"]',
  'x-operatum-auth-mode': 'reverse-proxy',
  'x-operatum-display-name': 'Alice%20Wonder',
  'x-operatum-timestamp': '1700000000000',
  'x-operatum-signature': '61c7803a6ffa2fa6cebc828d954504044bc339e27f34c7947552ff10ec263cd3',
});
// The exact canonical string the gateway signed (identity headers in
// pinned inventory order, absent optionals skipped, timestamp bound last,
// '\n'-joined). Byte-for-byte from the gateway's canonicalStringForSigning.
const GW_FIXTURE_CANONICAL =
  'x-operatum-user-id=00000000-0000-0000-0000-000000000001\n'
  + 'x-operatum-tenant-id=00000000-0000-0000-0000-000000000002\n'
  + 'x-operatum-email=alice%40example.com\n'
  + 'x-operatum-display-name=Alice%20Wonder\n'
  + 'x-operatum-role=builder\n'
  + 'x-operatum-build-id=00000000-0000-0000-0000-000000000003\n'
  + 'x-operatum-perms=["use"]\n'
  + 'x-operatum-auth-mode=reverse-proxy\n'
  + 'x-operatum-timestamp=1700000000000';

describe('gateway fixture — canonicalization + signature drift pin', () => {
  test('the gateway signature is HMAC-SHA256 over exactly the pinned canonical string', () => {
    // Independent recomputation: no module code involved. Pins WHAT was
    // signed (the canonical serialization), not just that verification
    // succeeds — so a symmetric drift on both sides still gets caught.
    const recomputed = createHmac('sha256', GW_FIXTURE_SECRET)
      .update(GW_FIXTURE_CANONICAL).digest('hex');
    assert.equal(recomputed, GW_FIXTURE_HEADERS['x-operatum-signature']);
  });

  test('readOperatumHeaders accepts the gateway-signed fixture end-to-end', () => {
    const out = readOperatumHeaders(GW_FIXTURE_HEADERS,
      { secret: GW_FIXTURE_SECRET, now: GW_FIXTURE_TS });
    assert.ok(out, 'main verifier must accept the gateway-signed fixture — '
      + 'a null here means the canonicalizations have DRIFTED');
    assert.equal(out.userId, '00000000-0000-0000-0000-000000000001');
    assert.equal(out.email, 'alice@example.com');
    assert.equal(out.displayName, 'Alice Wonder');
    assert.deepEqual(out.perms, ['use']);
  });

  test('the fixture does NOT verify under a different secret', () => {
    assert.equal(
      readOperatumHeaders(GW_FIXTURE_HEADERS,
        { secret: 'some-other-deploys-secret', now: GW_FIXTURE_TS }),
      null);
  });

  test('any covered fixture header tampered after signing is rejected', () => {
    for (const name of HEADER_ORDER.filter((n) => n !== 'x-operatum-display-name')) {
      const h = { ...GW_FIXTURE_HEADERS };
      // Keep each field individually well-formed so the SIGNATURE check
      // (not field validation) is what rejects it.
      h[name] = {
        'x-operatum-user-id': '00000000-0000-0000-0000-0000000000ff',
        'x-operatum-tenant-id': '00000000-0000-0000-0000-0000000000ff',
        'x-operatum-email': 'mallory%40example.com',
        'x-operatum-role': 'admin',
        'x-operatum-build-id': '00000000-0000-0000-0000-0000000000ff',
        'x-operatum-perms': '["use","build"]',
        'x-operatum-auth-mode': 'reverse-proxy',
      }[name];
      if (h[name] === GW_FIXTURE_HEADERS[name]) continue; // no-op tamper
      assert.equal(
        readOperatumHeaders(h, { secret: GW_FIXTURE_SECRET, now: GW_FIXTURE_TS }),
        null, `tampering ${name} must invalidate the signature`);
    }
    // Dropping the OPTIONAL covered header (display-name) must also break
    // the signature — it was included in the signed canonical string.
    const noDn = { ...GW_FIXTURE_HEADERS };
    delete noDn['x-operatum-display-name'];
    assert.equal(
      readOperatumHeaders(noDn, { secret: GW_FIXTURE_SECRET, now: GW_FIXTURE_TS }),
      null);
  });
});

// ── 2. pure-function enforcement via readOperatumHeaders({secret}) ─────

describe('readOperatumHeaders with a secret — fails closed', () => {
  test('correctly-signed set is accepted', () => {
    const h = sign(baseHeaders(), SECRET, FIXED_TS);
    const out = readOperatumHeaders(h, { secret: SECRET, now: FIXED_TS });
    assert.equal(out.userId, UUID_USER);
    assert.equal(out.role, 'builder');
  });

  test('unsigned (presence-only) set is REJECTED once a secret is configured', () => {
    assert.equal(readOperatumHeaders(baseHeaders(), { secret: SECRET, now: FIXED_TS }), null);
  });

  test('forged identity (header tampered after signing) is rejected', () => {
    const h = sign(baseHeaders(), SECRET, FIXED_TS);
    h['x-operatum-role'] = 'admin'; // privilege-escalation attempt
    assert.equal(readOperatumHeaders(h, { secret: SECRET, now: FIXED_TS }), null);
  });

  test('signature minted with the WRONG secret is rejected', () => {
    const h = sign(baseHeaders(), 'attacker-guess', FIXED_TS);
    assert.equal(readOperatumHeaders(h, { secret: SECRET, now: FIXED_TS }), null);
  });

  test('stale timestamp beyond the ±5min window is rejected (both clock directions inside pass)', () => {
    const h = sign(baseHeaders(), SECRET, FIXED_TS);
    assert.equal(readOperatumHeaders(h, { secret: SECRET, now: FIXED_TS + MAX_AGE_MS + 1 }), null);
    assert.equal(readOperatumHeaders(h, { secret: SECRET, now: FIXED_TS - MAX_AGE_MS - 1 }), null);
    // …and inside the window (either side) it still verifies.
    assert.notEqual(readOperatumHeaders(h, { secret: SECRET, now: FIXED_TS + MAX_AGE_MS - 1 }), null);
    assert.notEqual(readOperatumHeaders(h, { secret: SECRET, now: FIXED_TS - MAX_AGE_MS + 1 }), null);
  });

  test("EMPTY-STRING signature is rejected exactly like a missing one", () => {
    const missing = sign(baseHeaders(), SECRET, FIXED_TS);
    delete missing[SIG_HEADER];
    const empty = sign(baseHeaders(), SECRET, FIXED_TS);
    empty[SIG_HEADER] = '';
    assert.equal(readOperatumHeaders(missing, { secret: SECRET, now: FIXED_TS }), null);
    assert.equal(readOperatumHeaders(empty, { secret: SECRET, now: FIXED_TS }), null);
  });

  test('missing/empty/non-numeric timestamp is rejected', () => {
    for (const ts of [undefined, '', 'not-a-number']) {
      const h = sign(baseHeaders(), SECRET, FIXED_TS);
      if (ts === undefined) delete h[TS_HEADER];
      else h[TS_HEADER] = ts;
      assert.equal(readOperatumHeaders(h, { secret: SECRET, now: FIXED_TS }), null,
        `timestamp ${JSON.stringify(ts)} must fail closed`);
    }
  });

  test('malformed signatures return null, never throw (length + non-ASCII)', () => {
    // '中'.repeat(64) is the 71c2506 regression: 64 chars but >64 bytes
    // UTF-8, which made timingSafeEqual THROW pre-fix.
    for (const sig of ['deadbeef', 'a'.repeat(63), 'a'.repeat(65), '中'.repeat(64)]) {
      const h = sign(baseHeaders(), SECRET, FIXED_TS);
      h[SIG_HEADER] = sig;
      assert.equal(readOperatumHeaders(h, { secret: SECRET, now: FIXED_TS }), null,
        `signature ${JSON.stringify(sig.slice(0, 8))}… must fail closed without throwing`);
    }
  });

  test('custom maxAgeMs is honoured', () => {
    const h = sign(baseHeaders(), SECRET, FIXED_TS);
    assert.equal(
      readOperatumHeaders(h, { secret: SECRET, now: FIXED_TS + 2000, maxAgeMs: 1000 }), null);
    assert.notEqual(
      readOperatumHeaders(h, { secret: SECRET, now: FIXED_TS + 500, maxAgeMs: 1000 }), null);
  });

  test('NO secret configured → presence-only behaviour unchanged (unsigned accepted)', () => {
    const out = readOperatumHeaders(baseHeaders());
    assert.equal(out.userId, UUID_USER);
  });

  test('signed set still reads fine with NO secret configured (rollout: gateway signs first)', () => {
    // During rollout the gateway signs before the app enforces; the extra
    // x-operatum-timestamp/-signature headers must not break a
    // presence-only reader.
    const out = readOperatumHeaders(sign(baseHeaders(), SECRET, FIXED_TS));
    assert.equal(out.userId, UUID_USER);
  });
});

// ── 3. factory wiring — OPERATUM_GATEWAY_SIGNING_SECRET / opts.secret ──

// Swap the env var in only for the factory CONSTRUCTION — the factory
// resolves the secret once at construction time (src/header-mode.js:232).
function withEnv(value, fn) {
  const prev = process.env.OPERATUM_GATEWAY_SIGNING_SECRET;
  if (value === undefined) delete process.env.OPERATUM_GATEWAY_SIGNING_SECRET;
  else process.env.OPERATUM_GATEWAY_SIGNING_SECRET = value;
  try { return fn(); }
  finally {
    if (prev === undefined) delete process.env.OPERATUM_GATEWAY_SIGNING_SECRET;
    else process.env.OPERATUM_GATEWAY_SIGNING_SECRET = prev;
  }
}

describe('createOperatumAuthFromHeaders — OPERATUM_GATEWAY_SIGNING_SECRET wiring', () => {
  test('env set → unsigned headers 401 (fail closed)', async () => {
    const auth = withEnv(SECRET, () => createOperatumAuthFromHeaders());
    const res = makeRes();
    await auth.middleware()(
      { headers: baseHeaders() }, res,
      () => assert.fail('next must not fire on unsigned headers'));
    assert.equal(res.captured.status, 401);
    assert.equal(res.captured.body.error, 'unauthenticated');
  });

  test('env set → correctly-signed headers pass (next fires, req.operatum populated)', async () => {
    const auth = withEnv(SECRET, () => createOperatumAuthFromHeaders());
    const req = { headers: sign(baseHeaders(), SECRET, Date.now()) };
    const res = makeRes();
    let nextCalled = false;
    await auth.middleware()(req, res, () => { nextCalled = true; });
    assert.equal(nextCalled, true);
    assert.equal(req.operatum.userId, UUID_USER);
    assert.equal(req.operatum.role, 'builder');
  });

  test('env set → forged (tampered-after-signing) headers 401', async () => {
    const auth = withEnv(SECRET, () => createOperatumAuthFromHeaders());
    const headers = sign(baseHeaders(), SECRET, Date.now());
    headers['x-operatum-user-id'] = '00000000-0000-0000-0000-0000000000ff';
    const res = makeRes();
    await auth.middleware()({ headers }, res, () => assert.fail('forgery must not pass'));
    assert.equal(res.captured.status, 401);
  });

  test('env set → stale signature 401', async () => {
    const auth = withEnv(SECRET, () => createOperatumAuthFromHeaders());
    const headers = sign(baseHeaders(), SECRET, Date.now() - MAX_AGE_MS - 60_000);
    const res = makeRes();
    await auth.middleware()({ headers }, res, () => assert.fail('stale must not pass'));
    assert.equal(res.captured.status, 401);
  });

  test('env UNSET → legacy presence-only behaviour (unsigned accepted)', async () => {
    const auth = withEnv(undefined, () => createOperatumAuthFromHeaders());
    const req = { headers: baseHeaders() };
    let nextCalled = false;
    await auth.middleware()(req, makeRes(), () => { nextCalled = true; });
    assert.equal(nextCalled, true);
    assert.equal(req.operatum.userId, UUID_USER);
  });

  test("env set to '' → treated as unset (legacy behaviour), not as an empty key", async () => {
    const auth = withEnv('', () => createOperatumAuthFromHeaders());
    let nextCalled = false;
    await auth.middleware()({ headers: baseHeaders() }, makeRes(), () => { nextCalled = true; });
    assert.equal(nextCalled, true);
  });

  test('secret is captured at CONSTRUCTION — clearing the env later cannot downgrade', async () => {
    const auth = withEnv(SECRET, () => createOperatumAuthFromHeaders());
    // env var is restored/removed by withEnv before the request runs
    assert.equal(process.env.OPERATUM_GATEWAY_SIGNING_SECRET, undefined);
    const res = makeRes();
    await auth.middleware()(
      { headers: baseHeaders() }, res,
      () => assert.fail('enforcement must survive env mutation'));
    assert.equal(res.captured.status, 401);
  });

  test('opts.secret overrides the env var (embedding/test hook)', async () => {
    const auth = withEnv(undefined, () =>
      createOperatumAuthFromHeaders({ secret: SECRET }));
    const res = makeRes();
    await auth.middleware()({ headers: baseHeaders() }, res, () => assert.fail());
    assert.equal(res.captured.status, 401);
    // …and a set signed with the opts.secret passes.
    let nextCalled = false;
    await auth.middleware()(
      { headers: sign(baseHeaders(), SECRET, Date.now()) }, makeRes(),
      () => { nextCalled = true; });
    assert.equal(nextCalled, true);
  });
});
